Update xbox_marketplace.yml
- Bugfix when detecting Xbox Marketplace folder
- Added chunking of Xbox Marketplace stuff when commiting stuff

diff --git a/.github/workflows/xbox_marketplace.yml b/.github/workflows/xbox_marketplace.yml
--- a/.github/workflows/xbox_marketplace.yml
+++ b/.github/workflows/xbox_marketplace.yml
@@ -46,9 +46,35 @@ jobs:
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
-        git add Database/Xbox\ Marketplace/
         git add Database/xbox_marketplace_games.json
         git diff-index --quiet HEAD || git commit -m "Update Xbox Marketplace list of games"
+
+        # List all files and split into batches of 600, using numeric suffixes for chunk files
+        find "$(pwd)/Database/Xbox Marketplace/" -type f | split -l 600 --numeric-suffixes=1 - filelist_chunk_
+
+        # Initialize counter for part number
+        part=1
+
+        for chunk in filelist_chunk_*; do
+          echo "Processing chunk: $chunk"
+          cat $chunk | while read file; do
+            # Double check the file exists before trying to add it
+            if [ -f "$file" ]; then
+              git add "$file"
+            else
+              echo "Warning: File not found - $file"
+            fi
+          done
+
+          # Check if there are staged changes
+          if ! git diff-index --quiet HEAD; then
+            # Commit if there are changes
+            git commit -m "Update Xbox Marketplace games info & assets (Part $part)"
+            part=$((part+1))
+          else
+            echo "No changes to commit for chunk $chunk"
+          fi
+        done
         git push
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
